version: 2

models:
  - name: dim_browser
    description: User browsers
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: browser
        descrption: Browser name
        tests:
          - unique
          - not_null
      - name: ts_load
        description: Load datetime
        tests:
          - not_null

  - name: fact_visit
    description: Visits fact
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: fk_dim_geo
        tests:
          - relationships:
              to: ref('dim_geo')
              field: id